### ISSUE TITLE
Print macros after progress bar don't always work

### ISSUE THREAD

**Issue by maujim** [console-rs/indicatif#352]
When using `print!()` and `println!()` after a progress bar, the output isn't always printed. The example below shows a few cases of this.

<details>
<summary> to reproduce </summary>

src/main.rs
```rust
use indicatif::ProgressBar;

fn main() {
    let i = 1;

    let progress = ProgressBar::new(100);
    progress.inc(5);

    if i == 1 {
        println!("This doesn't print");
    } else if i == 2 {
        println!("This does print\n");
    } else if i == 3 {
        print!("This does print");
    } else if i == 4 {
        print!("This doesn't print\n");
    }
}
```

Cargo.toml
```toml
[package]
name = "minimum-reproducible"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = { version = "0.16.2" }
```
</details>
