### ISSUE TITLE
`elapsed` doesn't update during single long-running step or some parallel steps

### ISSUE THREAD

**Issue by mtkennerly** [console-rs/indicatif#558]
I'm not sure if this is a bug or an intentional design, but I noticed that `elapsed`/`elapsed_precise` don't update while a single step is running. I can definitely understand that for single-threaded iterators, but I was surprised that it's also true for parallel iterators. What would be the recommended way to handle this?

Also, with the parallel iterator, 16 of the iterations don't cause the progress bar to update. Incidentally, my system has 16 cores. It seems like I have to have more than 16 items in the iterator to see any updates.

### Cargo.toml
```toml
[package]
name = "prog-bar"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.5"
```

### main.rs
```rust
use std::{thread, time::Duration};
use indicatif::{ProgressIterator, ProgressBar, ProgressStyle};

fn main() {
    let xs = vec![1, 2, 3];

    let template = "{elapsed}, {elapsed_precise} {wide_bar} {pos} / {len}";
    let style = ProgressStyle::default_bar().template(&template).unwrap();
    let bar = ProgressBar::new(xs.len() as u64).with_style(style);

    _ = xs.iter().progress_with(bar).map(|_| {
        thread::sleep(Duration::from_secs(3));
    }).collect::<Vec<_>>();
}
```

### Output
> https://github.com/console-rs/indicatif/assets/4934192/6dcc17a4-4b2f-4051-aa6c-48c11adc2ff7

### Cargo.toml
```toml
[package]
name = "prog-bar"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = { version = "0.17.5", features = ["rayon"] }
rayon = "1.7.0"
```

### main.rs
```rust
use std::{thread, time::Duration};
use indicatif::{ParallelProgressIterator, ProgressBar, ProgressStyle};
use rayon::prelude::{IntoParallelIterator, ParallelIterator};

fn main() {
    println!("Cores: {}", thread::available_parallelism().unwrap());

    let xs = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

    let template = "{elapsed}, {elapsed_precise} {wide_bar} {pos} / {len}";
    let style = ProgressStyle::default_bar().template(&template).unwrap();
    let bar = ProgressBar::new(xs.len() as u64).with_style(style);

    _ = xs.into_par_iter().progress_with(bar).map(|x| {
        thread::sleep(Duration::from_secs(x));
    }).collect::<Vec<_>>();
}
```

### Output
> https://github.com/console-rs/indicatif/assets/4934192/2d651360-42b3-434b-8b5e-5ace0e70b603
